### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SzaszArnold** [HMS-Core/hms-health-demo-java#1]
Hi. 
Can you write what permissions you asked for from Huawei, in Huawei Health Kit.

**Comment by healthkit-hms** [comment]
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/apply-kitservice-0000001050071707

**Comment by healthkit-hms** [comment]
https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/scopes-0000001050092713-V5

**Comment by healthkit-hms** [comment]
For details, see the preceding two links.

**Comment by healthkit-hms** [comment]
I'm an internal account. I've applied for all permissions.

**Comment by SzaszArnold** [comment]
Thank you!
