### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AkiraDate** [HMS-Core/hms-health-demo-java#3]
is this program runs on any device or it's only run on hawei devices?

**Comment by Mike-mei** [comment]
Client development and access requirements：
**1. Only Huawei phones are supported**
2. HMS Core (APK) 4.0.2.300 or later has been installed
3. The phone you use is running EMUI 8.1 or later

**Comment by AkiraDate** [comment]
then which device that can be scanned?

**Comment by AkiraDate** [comment]
i have honor band 5 is it scannable because i dont get scancallback from the app

**Comment by healthkit-hms** [comment]
So far we only support devices that they use bluetooth protocols according to https://www.bluetooth.com/specifications/gatt/services/ . There are some APPs designed for scanning BLE device's protocols in apps market you may look for it.
