### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AkiraDate** [HMS-Core/hms-health-demo-java#5]
I have honor band 5 and it seems the app cannot discover the smart band, how can you help me fix it?

**Comment by healthkit-hms** [comment]
@AkiraDate BleController supports standard Bluetooth protocols according to https://www.bluetooth.com/specifications/gatt/services/  , so please make sure that your device has the service protocols and exposes to developers. Besides that, please pay attention to our SensorsController part under Client Development section in Development Guide [https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sensorscontroller-develop-0000001050069728](url)
Please let us know if this is helpful. We will keep following up under this post.

**Comment by healthkit-hms** [comment]
@AkiraDate BleController supports standard Bluetooth protocols according to https://www.bluetooth.com/specifications/gatt/services/  , so please make sure that your device has the service protocols and exposes to developers. Besides that, please pay attention to our SensorsController part under Client Development section in Development Guide [https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sensorscontroller-develop-0000001050069728](url)
Please let us know if this is helpful. We will keep following up under this post.

**Comment by AkiraDate** [comment]
I already did it the way on the development guide and your code so I'm in a bind now

**Comment by healthkit-hms** [comment]
@AkiraDate Can you discover the smart band by BleController now? Before you register a listener for it, please call the saveDevice() method.
