### ISSUE TITLE
Getting status code 10

### ISSUE THREAD

**Issue by AndroidDeveloperMCT** [HMS-Core/hms-health-demo-java#6]
Hello team,

I am developing an Android app to get user's daily steps from Huawei health. In order to achieve this, I followed the technical docs from this link [ https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/apply-id-0000001050069756-V5 ] and registered the Huawei ID and Health Kit of app ID [ xxxxxxxx ] with the new package name. When I run the demo app with a new package name it is giving me status code 10.

ConnectionResult.DEVELOPER_ERROR
10
HMS SDK internal error. AIDL connection succeeded, but the AIDL handle was not obtained. This is usually caused by a configuration error.
Contact Huawei technical support. This problem rarely occurs.\

Thanks

**Comment by Mike-mei** [comment]
Can you provide your log for us to locate your error? 
And we notice that you are in India from you GiHub account. Huawei health kit is not supported in India now. This [link](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/countries-regions-0000001058740695-V5) lists the countries and regions we support now.

**Comment by AndroidDeveloperMCT** [comment]
Yes, I am from India ( also know that India is not listed in the list ), but I am working for a UK-based account ( as a team member ). Please check the video, facing some developer configuration error.

https://user-images.githubusercontent.com/25820087/105350560-5ed2ba00-5c11-11eb-880a-d2d6b6d93270.mp4

**Comment by healthkit-hms** [comment]
Hi, May you cut some ss when error occur ? The vedio can not be seen for bad nowrok

**Comment by AndroidDeveloperMCT** [comment]
Yes sure

![vlcsnap-2021-01-21-18h06m50s225](https://user-images.githubusercontent.com/25820087/105352177-93477580-5c13-11eb-8209-02a78b3a641b.png)

![vlcsnap-2021-01-21-18h06m55s940](https://user-images.githubusercontent.com/25820087/105352186-97739300-5c13-11eb-89f3-202018da2fe8.png)

**Comment by healthkit-hms** [comment]
sory, the picture also can not be seen , may you create a ticket in our developer website and attach your ss and vedio

**Comment by healthkit-hms** [comment]
https://developer.huawei.com/consumer/en/support/feedback/#/
Here is our online feedback approach . and choose HMS Core-Health Kit and create a ticket to us

**Comment by AndroidDeveloperMCT** [comment]
Yes Thanks, I already mailed the query on this email [ developerapac@huawei.com ]

**Comment by healthkit-hms** [comment]
The 907135003 error usually occur in such situation :
1. The HMS version is too low, you may need clear Hms core application cache , data and update it ;
2. The project setting in you project may need be checked following the guide in (https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/integrating-sdk-0000001050069724)

**Comment by AndroidDeveloperMCT** [comment]
@healthkit-hms Hello,

1) My HMS version is updated.
2) I am following the same from HMSCore-Guide integration, also I am running this repo but still, it is giving me this. Is it because I am trying to authorize from an Indian Huawei account? But I also tried with  UK based account and the problem is same.

**Comment by healthkit-hms** [comment]
may you please cut the log when the error occurs (please use the logcat to get a full log) to us ?

**Comment by AndroidDeveloperMCT** [comment]
I've got the answer on my ticket in the developer account, that it requires a Huawei device in order to get Health data. Yesterday I order a Huawei device to test Health Kit. 

Closing the issue as of now
