### ISSUE TITLE
This method 'sampleSet.getSamplePoints()' always returning null

### ISSUE THREAD

**Issue by AndroidDeveloperMCT** [HMS-Core/hms-health-demo-java#7]
Hello everyone, I am working on an app to get daily steps data from Huawei health using Huawei devices only. I clone this GitHub repo, changed the package name, and created an app and everything on the Huawei developer account. 

When I running the method readToday() from HealthKitDataControllerActivity.java class, it is coming in 'addOnSuccessListener' but 'sampleSet.getSamplePoints()' always returning null. I have around 2000+ steps in my Huawei health.

Can anyone help me out, what I am doing incorrectly?

**Comment by healthkit-hms** [comment]
please refer to the FAQ in the website（https://developer.huawei.com/consumer/en/doc/faq-0000001050116769-V5）.
this FAQ: Calling the DataController.read, readDailySummation, readTodaySummation, or ActivityRecordsController.getActivityRecord API does not return any data from the HUAWEI Health app. What should I do?

**Comment by AndroidDeveloperMCT** [comment]
Okay thanks
